In [1]:
import random
import math

data = [random.randint(10, 100) for _ in range(5)]
print("Dataset:", data)


Dataset: [65, 69, 57, 44, 65]


In [2]:
mean = sum(data) / len(data)
print("Mean:", mean)

Mean: 60.0


In [3]:
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_dev = math.sqrt(variance)
print("Standard Deviation:", std_dev)


Standard Deviation: 8.899438184514796


In [4]:
z_scores = [(x - mean) / std_dev for x in data]
print("Z-scores:", z_scores)


Z-scores: [0.5618332187193683, 1.0112997936948631, -0.337099931231621, -1.7978662999019788, 0.5618332187193683]


standard deeviation using scikit learn

In [25]:
#finding standard devaition using scikitlearn

#it is used to generate a datset of random integer between 1 and 100000

import numpy as np 
import pandas as pd

np.random.seed(45)
X = np.random.randint(1,100000,size = 5)
print ("Dataset:", X)

Dataset: [ 6559 63108  6013 60961 12896]


In [27]:
from sklearn.preprocessing import StandardScaler    
s = StandardScaler()
X_scaled = s.fit_transform(X.reshape(-1, 1))

#using this print we get ouput as this 
print(X_scaled)
# [[-0.50880213]
#  [-1.01104002]
#  [ 1.54336175]
#  [ 0.80575974]
#  [-0.82927934]]


#using this print we get ouput as this 
#print( X_scaled.flatten())
#[-0.50880213 -1.01104002  1.54336175  0.80575974 -0.82927934]



[[-0.88602715]
 [ 1.25989931]
 [-0.90674681]
 [ 1.17842476]
 [-0.64555011]]


In [30]:
mean = np.mean(X_scaled)
print(mean)

-4.4408920985006264e-17


In [31]:
# standard deviation = np.std(X_scaled)
# print(standard deviation)

sq = 0
for i in X_scaled:
    #sq += (i - mean) ** 2
    sq = sq + ((i - mean) ** 2)
    std = (sq/len(X_scaled)) ** 0.5
print(std)

[1.]


In [18]:
X_scaled = []
for i in X_scaled:
    X_scaled.append((i - mean) / std)
print(X_scaled)

[]


Normalization using scikit learn

Normalization scales numerical data so that values fall within a fixed range, usually 0 to 1.
It’s super important for algorithms like:

KNN

Neural Networks

Gradient Descent–based models

SVM (distance-based)


$X_{\text{norm}} = \frac{X - X_{\min}}{X_{\max} - X_{\min}}$



In [34]:
# min  = np.min(X)
# max = np.max(X)
# print (max)
# print (min)

min,max = X[0],X[0]
for i in X:
    if i>max:
        max = i
    elif i<min:
        min = i
print(max)
print(min)

63108
6013


In [35]:
X_scaled2 = []
for i in X:
    X_scaled2.append(((i - min)/(max - min)))
print(X_scaled)

[[-0.88602715]
 [ 1.25989931]
 [-0.90674681]
 [ 1.17842476]
 [-0.64555011]]
